CREATE TABLE lists
(
    id         INT          NOT NULL AUTO_INCREMENT,
    title      VARCHAR(256) NOT NULL,
    user_id    INT          NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_lists PRIMARY KEY (id)
);