CREATE TABLE cards
(
    id         INT          NOT NULL AUTO_INCREMENT,
    title      VARCHAR(256) NOT NULL,
    list_id    INT,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PK_cards PRIMARY KEY (id),
    CONSTRAINT FK_cards_list_id FOREIGN KEY (list_id) REFERENCES lists (id)
        ON DELETE SET NULL ON UPDATE CASCADE
);