name: CI

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: I/O-free tests
        run: |
          chmod +x mvnw
          ./mvnw clean verify -Dgroups="! io"

      - name: I/O-based tests
        run: |
          chmod +x mvnw
          ./mvnw clean verify -Dgroups=io

      - name: Build with Maven
        run: |
          chmod +x mvnw
          ./mvnw clean install -Dspring.profiles.active=prod -DskipTests=true